name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    name: PHPUnit (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.4', '8.5']
    steps:
      - uses: actions/checkout@v6

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer install --no-interaction --prefer-dist

      - run: vendor/bin/phpunit

  static-analysis:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - run: composer install --no-interaction --prefer-dist

      - run: vendor/bin/phpstan analyse

  code-style:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - run: composer install --no-interaction --prefer-dist

      - run: vendor/bin/php-cs-fixer check --diff

  code-coverage:
      name: Code Coverage
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v6

          - uses: shivammathur/setup-php@v2
            with:
                php-version: '8.4'
                coverage: xdebug

          - run: composer install --no-interaction --prefer-dist

          - run: vendor/bin/phpunit --log-junit test-results.xml --coverage-openclover=code-coverage.xml

          - name: Upload test results to Codecov.io
            uses: codecov/codecov-action@v6
            with:
                token: ${{ secrets.CODECOV_TOKEN }}
                report_type: test_results
                disable_search: true
                files: ./test-results.xml

          - name: Upload code coverage data to Codecov.io
            uses: codecov/codecov-action@v6
            with:
                token: ${{ secrets.CODECOV_TOKEN }}
                report_type: coverage
                disable_search: true
                files: ./code-coverage.xml
